### ISSUE TITLE
Some errors on Mac

### ISSUE THREAD

**Issue by sjogr3n** [guwidoe/VBA-StringTools#14]
Hello! I am quite new to VBA but found your profile on SO since I also need to use a specific encoding. However, when I run the module on Mac (on Apple Silicon) with updated Excel I get an issue I don't seem to be able to surpass.

Using the function call:

```
Dim theString As String
theString = "abcd"
Dim b() As Byte: b = Encode(theString, cpIBM437) 
```
I get stuck at the following line:

```
Static replacementChars As Collection
If replacementChars Is Nothing Then replacementChars = New Collection
```

Here, I get the error message that there is a compiling error: the variable isn't optional.

Assuming I'm understanding the syntax of VBA correctly, it is supposed to add a **Set**:

```
Static replacementChars As Collection
If replacementChars Is Nothing Then Set replacementChars = New Collection
```

Using this as an assumed fix, I then get a type error at the line:

`SetApiErrorNumber = 0`

Looking at other parts of the script, this might be meant to say

`SetApiErrorNumber 0`

However, after this (again presumed) fix which let's the function continue, I then run into another type error with regards to the `iconv()` function at the very next line:

`irrevConvCount = iconv(cd, inBuf, inBytesLeft, outBuf, outBytesLeft)`

Here, I don't really understand what's going wrong. Since VBA isn't very verbose in its error messaging, at least by default, I'm unsure what the cause is – you might have a better idea. Any help would be greatly appreciated – I'm happy to assist with testing if I can, although my schedule is somewhat busy in the coming days. I would in any case like to thank you for creating the software and hope that this is the right way of contacting/reporting these errors. Otherwise, please let me know and I'll redo it some other (better) way.

Best regards,
sjogr3n

**Comment by guwidoe** [comment]
Hi @sjogr3n, thanks for raising the issue!
It's funny because I noticed some of the things you brought up a few days ago and worked on a fix which led me down a rabbit hole that overwhelmed me a bit and prevented me from pushing anything in the end. Now you are motivating me to look into it again!

You are absolutely right about the missing `Set` and about the wrong use of `SetApiErrorNumber`. I have written a bunch of code there that I forgot to test on Mac because that is always a hassle for me.

I have already looked into the rest aswell, and I think I know how to fix everything, I'll push it as soon as I have time!

**Comment by sjogr3n** [comment]
Thanks for the response, and thanks for looking further into it! Please let me know if I can assist in testing in any way. Have a nice weekend!

**Comment by guwidoe** [comment]
Hi @sjogr3n, I finally got to look into this. 
I now pushed an extensive rework of the `Encode`, `Decode` and `Transcode` API wrapper functions (5e20a51) and I hope that should resolve this issue. 
Please let me know if the current version still causes issues or if this is now resolved :)

**Comment by guwidoe** [comment]
Hi @sjogr3n , any chance you'll get to test the new implementation for your usecase? Did you manage to solve your problem in some way? Are you still working on this? I'd appreciate some feedback, otherwise I'll eventually close this issue :)

**Comment by guwidoe** [comment]
Thanks for the info! I'll close it in the meantime :) 
If you get to test it eventually that would be great and all feedback is much appreciated!
